### ISSUE TITLE
Allow searching through the list

### ISSUE THREAD

**Issue by JeromeDeLeon** [maixiaojie/git-emoji#1]
It would be better if we are allowed to search through the list rather than scrolling and selecting :smiley:

**Comment by maixiaojie** [comment]
@JeromeDeLeon it's ready a excellent suggestion, i will prove it when i am not busy.

**Comment by JeromeDeLeon** [comment]
Nice! That would be awesome.

**Comment by maixiaojie** [comment]
@JeromeDeLeon yes, I have been pushlished it! 👍

**Comment by maixiaojie** [comment]
and I want to use origin emoji like 🐛 , not `:bug:` 。always on the road ❤️

**Comment by maixiaojie** [comment]
@all-contributors please add @JeromeDeLeon  for prove

**Comment by maixiaojie** [comment]
@all-contributors please add @JeromeDeLeon for design

**Comment by maixiaojie** [comment]
@all-contributors please add @maixiaojie for Code

**Comment by maixiaojie** [comment]
@all-contributors please add @JeromeDeLeon for Code

**Comment by maixiaojie** [comment]
@all-contributors please add @JeromeDeLeon for Code

**Comment by maixiaojie** [comment]
@all-contributors please add @JeromeDeLeon for Code

**Comment by maixiaojie** [comment]
@all-contributors please add @JeromeDeLeon for Code
